### ISSUE TITLE
Supported OS?

### ISSUE THREAD

**Issue by minexew** [SmaugEditor/Smaug#3]
Hi, just curious, what are the system requirements for this?

Screenshots in the readme would be also really cool :))

**Comment by ozxybox** [comment]
I haven't had time to determine the exact system requirements yet, but it needs a machine with at least OpenGL or DX9 and 16 MBs of ram. It has full Windows 10 support, and Linux support is in progress; it runs, just the objects are black at the moment.
Good idea with the readme! I'll have to do so shortly! For now, here's a video though 😁 https://www.youtube.com/watch?v=gS1_YLvQI-k

**Comment by minexew** [comment]
Thanks, it built out-of-the-box on Win10 with $whatever_mingw_version_i_have

**Comment by ozxybox** [comment]
Awesome! Glad to hear it built easily!
